version: '3.4'

services:
  seq:
    image: datalust/seq:latest

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest 

  rabbitmq:
    image: rabbitmq:3-management-alpine


  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

  auction.api:
    image: ${DOCKER_REGISTRY-}auctionapi
    build:
      context: .
      dockerfile: Services/Contacting/Contacting.API/Dockerfile


  bidding.api:
    image: ${DOCKER_REGISTRY-}biddingapi
    build:
      context: .
      dockerfile: Services/Bidding/Bidding.API/Dockerfile


  location.api:
    image: ${DOCKER_REGISTRY-}locationapi
    build:
      context: .
      dockerfile: Services/Location/Location.API/Dockerfile


  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile


  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Services/Product/Product.API/Dockerfile


  streaming.api:
    image: ${DOCKER_REGISTRY-}streamingapi
    build:
      context: .
      dockerfile: Services/Streaming/Streaming.API/Dockerfile


  webhooks.api:
    image: ${DOCKER_REGISTRY-}webhooksapi
    build:
      context: .
      dockerfile: Services/Webhooks/Webhooks.API/Dockerfile

